baseURL = 'https://robinroy.xyz/'
locale = 'en-us'
title = 'Robin Roy'
theme = 'hugo-bearblog'
enableRobotsTXT = true

[params]
hideMadeWithLine = true
favicon = 'favicon.svg'
description = "hi i'm robin welcome to my little place on the internet"